Class RalseiGun_RalseiTauntHandler : EventHandler
{
	Override Void WorldThingDied(WorldEvent e)
	{
		Let victim = e.Thing;
		Let source = e.Thing.Target;		
		If((victim.bISMONSTER || victim.bCOUNTKILL) && source is "RalseiGun_Ralsei")
		{
			If(Source && Source.Health > 0)			
			{
				If(Random(0, 3) == 1 || Victim.bBOSS) 
				{
					Source.SetStateLabel("Victory");
				}
			}
		}
	}
}